name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/
    - name: Test
      run: dotnet test test/ --verbosity normal --runtime net6.0 p:NoWarm=NETSDK1179
    - name: Publish WSDOT WZDX-Client
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Wsdot.Wzdx.Models.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: WZDx Client
